// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBibGcos3SLo9oC1KU9wNmd-_KR7qp0JAs',
    appId: '1:731395395048:web:569414ae950c5e4fc7285d',
    messagingSenderId: '731395395048',
    projectId: 'telegram-flutter-0',
    authDomain: 'telegram-flutter-0.firebaseapp.com',
    storageBucket: 'telegram-flutter-0.appspot.com',
    measurementId: 'G-10WZBM9D2B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3eytxht2vs8nZ3oTlBhcM9rk_GxWVejA',
    appId: '1:731395395048:android:f97fad934957b29dc7285d',
    messagingSenderId: '731395395048',
    projectId: 'telegram-flutter-0',
    storageBucket: 'telegram-flutter-0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZASd1Nv-jPH3mBB2xG3_o3DjgJxoY9-8',
    appId: '1:731395395048:ios:07ba54a7ea2828c5c7285d',
    messagingSenderId: '731395395048',
    projectId: 'telegram-flutter-0',
    storageBucket: 'telegram-flutter-0.appspot.com',
    iosBundleId: 'com.example.untitled1',
  );
}
